-- DataWarehouse (PostgreSQL): dimensions.
--
-- Run after 02_paylocity_staging.sql, as the database owner. Safe to re-run:
-- tables and seed rows are only created when missing, and the load functions
-- are CREATE OR REPLACE. Loading happens in "Integration"."RefreshWarehouse"()
-- (04_facts.sql), which the loader calls at the end of every run.
--
-- Every dimension has an "Unknown" row with key -1, so a fact row whose
-- employee or date can't be matched still loads and is easy to find.

CREATE SCHEMA IF NOT EXISTS "Dimension";

-- Where each history-keeping dimension has got to, and where its history starts.
CREATE TABLE IF NOT EXISTS "Integration"."DimensionLoad" (
    "TableName"       text PRIMARY KEY,
    "HistoryStartUtc" timestamp,      -- snapshots before this are ignored
    "LastSnapshotUtc" timestamp,      -- newest snapshot applied so far
    "LastLoadedAt"    timestamptz,
    "Notes"           text
);

-- ── Date ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Dimension"."Date" (
    "DateKey"     integer PRIMARY KEY,           -- yyyymmdd, e.g. 20261004; -1 = Unknown
    "Date"        date UNIQUE,
    "Year"        integer,
    "Quarter"     integer,
    "MonthNumber" integer,
    "MonthName"   text,
    "YearMonth"   text,                          -- '2026-10'
    "MonthStart"  date,
    "WeekStart"   date,                          -- Monday
    "IsoWeek"     integer,
    "DayOfWeek"   integer,                       -- 1 = Monday ... 7 = Sunday
    "DayName"     text,
    "IsWeekday"   boolean
);

INSERT INTO "Dimension"."Date" ("DateKey", "MonthName", "DayName")
VALUES (-1, 'Unknown', 'Unknown')
ON CONFLICT ("DateKey") DO NOTHING;

INSERT INTO "Dimension"."Date"
SELECT to_char(d, 'YYYYMMDD')::integer,
       d,
       extract(year FROM d)::integer,
       extract(quarter FROM d)::integer,
       extract(month FROM d)::integer,
       to_char(d, 'FMMonth'),
       to_char(d, 'YYYY-MM'),
       date_trunc('month', d)::date,
       date_trunc('week', d)::date,
       extract(week FROM d)::integer,
       extract(isodow FROM d)::integer,
       to_char(d, 'FMDay'),
       extract(isodow FROM d) < 6
FROM generate_series(date '2015-01-01', date '2035-12-31', interval '1 day') AS g (ts),
     LATERAL (SELECT g.ts::date AS d) AS x
ON CONFLICT ("DateKey") DO NOTHING;

-- ── Employee ────────────────────────────────────────────────────────────────
-- Type 2: a new version every time a tracked attribute changes, so facts can
-- see the employee as they were on the day. One row per employee per version:
--   "ValidFrom"/"ValidTo"  when this version applied ("ValidTo" NULL = current)
--   "IsCurrent"            exactly one current version per employee
--   "IsDeleted"            soft delete: the employee disappeared from the
--                          Paylocity roster. Their history stays; the current
--                          version is a copy marked deleted. If they reappear,
--                          a new live version starts.
-- "IsActive" is Paylocity's own active flag (the roster also lists inactive
-- people); it is an attribute, not a delete.

CREATE TABLE IF NOT EXISTS "Dimension"."Employee" (
    "EmployeeKey"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId"           text        NOT NULL,     -- Paylocity Employee Id
    "FirstName"            text,
    "LastName"             text,
    "FullName"             text,
    "JobTitle"             text,
    "SupervisorEmployeeId" text,
    "IsActive"             boolean,
    "PositionCode"         text,
    "PositionJobTitle"     text,
    "IsDeleted"            boolean     NOT NULL DEFAULT false,
    "ValidFrom"            timestamp   NOT NULL,     -- UTC, the roster snapshot's time
    "ValidTo"              timestamp,
    "IsCurrent"            boolean     NOT NULL,
    "RowHash"              text        NOT NULL,     -- of the tracked attributes
    "SourceFileId"         bigint,
    "InsertedAt"           timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt"            timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Employee_Current"
    ON "Dimension"."Employee" ("EmployeeId") WHERE "IsCurrent";
CREATE INDEX IF NOT EXISTS "IX_Employee_Version" ON "Dimension"."Employee" ("EmployeeId", "ValidFrom");

INSERT INTO "Dimension"."Employee"
    ("EmployeeKey", "EmployeeId", "FullName", "ValidFrom", "IsCurrent", "RowHash")
VALUES (-1, 'Unknown', 'Unknown', '1900-01-01', true, '')
ON CONFLICT ("EmployeeKey") DO NOTHING;

-- History starts at the first roster in the current report layout. Before
-- 2026-10-02 14:31 UTC the report had a "Position Family Codes" column instead
-- of "Position Code" / "Position Job Title", so starting earlier would show
-- every employee's position changing that day when nothing did. Verified: no
-- other attribute changed for anyone across the earlier rosters.
INSERT INTO "Integration"."DimensionLoad" ("TableName", "HistoryStartUtc", "Notes")
VALUES ('Dimension.Employee', '2026-10-02 14:31:41',
        'Starts at the first Employee_Information file with Position Code / Position Job Title columns')
ON CONFLICT ("TableName") DO NOTHING;

-- Apply every roster snapshot not yet applied, oldest first. Returns counts.
CREATE OR REPLACE FUNCTION "Dimension"."LoadEmployee"() RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
    snapshot   record;
    history_start timestamp;
    applied_to timestamp;
    n int;
    n_snapshots int := 0;
    n_closed    int := 0;
    n_versions  int := 0;
    n_deleted   int := 0;
BEGIN
    SELECT "HistoryStartUtc", "LastSnapshotUtc" INTO history_start, applied_to
    FROM "Integration"."DimensionLoad" WHERE "TableName" = 'Dimension.Employee' FOR UPDATE;

    CREATE TEMP TABLE IF NOT EXISTS employee_snapshot (
        "EmployeeId" text PRIMARY KEY, "FirstName" text, "LastName" text, "JobTitle" text,
        "SupervisorEmployeeId" text, "IsActive" boolean, "PositionCode" text,
        "PositionJobTitle" text, "RowHash" text
    ) ON COMMIT DROP;
    CREATE TEMP TABLE IF NOT EXISTS employee_gone (LIKE "Dimension"."Employee") ON COMMIT DROP;

    FOR snapshot IN
        SELECT DISTINCT "FileId", "SnapshotUtc"
        FROM "Paylocity"."EmployeeInformationSnapshot"
        WHERE "SnapshotUtc" >= coalesce(history_start, '-infinity')
          AND "SnapshotUtc" >  coalesce(applied_to, '-infinity')
        ORDER BY "SnapshotUtc", "FileId"
    LOOP
        n_snapshots := n_snapshots + 1;

        TRUNCATE employee_snapshot;
        INSERT INTO employee_snapshot
        SELECT DISTINCT ON ("EmployeeId")
               "EmployeeId", "FirstName", "LastName", "JobTitle", "SupervisorEmployeeId", "IsActive",
               "PositionCode", "PositionJobTitle",
               md5(jsonb_build_array("FirstName", "LastName", "JobTitle", "SupervisorEmployeeId",
                                     "IsActive", "PositionCode", "PositionJobTitle")::text)
        FROM "Paylocity"."EmployeeInformationSnapshot"
        WHERE "FileId" = snapshot."FileId" AND "EmployeeId" IS NOT NULL
        ORDER BY "EmployeeId";

        -- Close the current version of anyone whose attributes changed, or who is
        -- back after being deleted.
        UPDATE "Dimension"."Employee" AS e
        SET "ValidTo" = snapshot."SnapshotUtc", "IsCurrent" = false, "UpdatedAt" = now()
        FROM employee_snapshot AS s
        WHERE e."EmployeeId" = s."EmployeeId" AND e."IsCurrent" AND e."EmployeeKey" > 0
          AND (e."RowHash" <> s."RowHash" OR e."IsDeleted");
        GET DIAGNOSTICS n = ROW_COUNT; n_closed := n_closed + n;

        -- A new current version for everyone in the roster without one: new
        -- employees, plus those just closed above.
        INSERT INTO "Dimension"."Employee"
            ("EmployeeId", "FirstName", "LastName", "FullName", "JobTitle", "SupervisorEmployeeId",
             "IsActive", "PositionCode", "PositionJobTitle", "ValidFrom", "IsCurrent", "RowHash", "SourceFileId")
        SELECT s."EmployeeId", s."FirstName", s."LastName",
               nullif(concat_ws(' ', s."FirstName", s."LastName"), ''),
               s."JobTitle", s."SupervisorEmployeeId", s."IsActive", s."PositionCode", s."PositionJobTitle",
               snapshot."SnapshotUtc", true, s."RowHash", snapshot."FileId"
        FROM employee_snapshot AS s
        WHERE NOT EXISTS (SELECT 1 FROM "Dimension"."Employee" AS e
                          WHERE e."EmployeeId" = s."EmployeeId" AND e."IsCurrent");
        GET DIAGNOSTICS n = ROW_COUNT; n_versions := n_versions + n;

        -- Soft delete anyone current who is no longer in the roster: close their
        -- version, then add a current copy marked deleted.
        TRUNCATE employee_gone;
        WITH closed AS (
            UPDATE "Dimension"."Employee" AS e
            SET "ValidTo" = snapshot."SnapshotUtc", "IsCurrent" = false, "UpdatedAt" = now()
            WHERE e."IsCurrent" AND NOT e."IsDeleted" AND e."EmployeeKey" > 0
              AND NOT EXISTS (SELECT 1 FROM employee_snapshot AS s WHERE s."EmployeeId" = e."EmployeeId")
            RETURNING e.*
        )
        INSERT INTO employee_gone SELECT * FROM closed;

        INSERT INTO "Dimension"."Employee"
            ("EmployeeId", "FirstName", "LastName", "FullName", "JobTitle", "SupervisorEmployeeId",
             "IsActive", "PositionCode", "PositionJobTitle", "IsDeleted", "ValidFrom", "IsCurrent",
             "RowHash", "SourceFileId")
        SELECT g."EmployeeId", g."FirstName", g."LastName", g."FullName", g."JobTitle", g."SupervisorEmployeeId",
               g."IsActive", g."PositionCode", g."PositionJobTitle", true, snapshot."SnapshotUtc", true,
               g."RowHash", snapshot."FileId"
        FROM employee_gone AS g;
        GET DIAGNOSTICS n = ROW_COUNT; n_deleted := n_deleted + n;

        UPDATE "Integration"."DimensionLoad"
        SET "LastSnapshotUtc" = snapshot."SnapshotUtc"
        WHERE "TableName" = 'Dimension.Employee';
    END LOOP;

    UPDATE "Integration"."DimensionLoad" SET "LastLoadedAt" = now() WHERE "TableName" = 'Dimension.Employee';

    RETURN jsonb_build_object(
        'snapshots_applied', n_snapshots,
        'new_employees',     n_versions - n_closed,
        'changed',           n_closed,
        'deleted',           n_deleted);
END;
$$;
